### PR TITLE
Add better type for flags with default value

### PR DESCRIPTION
**Pull request by frangio**
A flag with a default value was being typed as as `T | undefined`. For example the following would not type:

```typescript
      const out = parse([], {
        flags: {
          foo: flags.string({ default: 'baz' }),
          bar: flags.integer({ default: 42 }),
        }
      })
      const foo: string = out.flags.foo;
      const bar: number = out.flags.bar;
```

I added a special case in the type for this, the same way that `required: true` works.

Making the flag required is a workaround to get the above to type, but this is undesirable because it incorrectly shows the flag as required in the help.

### CODE REVIEW

**Comment by frangio** [comment]
Not sure why the CI is not running. A [previous run](https://circleci.com/gh/oclif/parser/tree/pull%2F53) had passed.

**Comment by frangio** [comment]
@RasPhilCo any chance to get this small PR merged? :pray:

Thanks!

**Comment by RasPhilCo** [comment]
Nice! Looking into why Circle stopped running...

**Comment by frangio** [comment]
The CI failure seems unrelated to this PR. `master` is failing for the same reason. What do you suggest? I can look into fixing it. The problem is an implicit `any` type.

**Comment by RasPhilCo** [comment]
Can you push another commit with a comment or something small to trigger CI again? I had to re-add the repo and I think there's a caching issue.

**Comment by frangio** [comment]
I fixed what was causing the tests to fail.

This coverage report is very odd-looking though. :thinking: -91.36%?

**Pull request merged**
